name: Node.js CI

on:
  push: 
    branches: [ master ]
  pull_request:
    branches:  [ master ]

jobs: 
  build_steps:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}          
      - run: npm ci
      - run: npm run test  
  push_to_docker_hub_steps: 
    runs-on: ubuntu-latest
    needs: [build_steps]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: set up QEMU
        uses: docker/setup-qemu-action@1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with: 
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/nodejs-api-fake:latest
     
               