name: Quality

on:
  workflow_dispatch:
  pull_request: 
    types: [opened, reopened, synchronize]
    branches: [ master ]

jobs: 
  build_steps:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}          
      - run: npm ci
      - run: npm run test  

      - name: Build docker image
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t api-fake:$PULL_REQUEST_NUMBER .
          echo "image=api-fake:$PULL_REQUEST_NUMBER" >> $GITHUB_OUTPUT      
     